
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom

    # Wheel configuration
    left_wheel_names: ["wheel_front_left_joint", "wheel_back_left_joint"]
    right_wheel_names: ["wheel_front_right_joint", "wheel_back_right_joint"]
    wheel_separation: 0.4  # Distance between left and right wheels
    wheel_radius: 0.07    

    # Odometry configuration
    publish_wheel_joint_controller_state: true
    publish_odom: true
    enable_odom_tf: true  # Publish odom->base_link transform
    
    # Command interfaces
    use_stamped_vel: false  # Use geometry_msgs/Twist instead of TwistStamped
    
    # Velocity limits (matching AVR capabilities)
    linear:
      x:
        max_velocity: 0.5
        min_velocity: -0.5
        max_acceleration: 1.0
        min_acceleration: -1.0
    angular:
      z:
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
        min_acceleration: -1.0
    
    # PID gains for velocity control
    pid_gains:
      wheel_front_left_joint: {p: 0.5, i: 0.1, d: 0.0}
      wheel_front_right_joint: {p: 0.5, i: 0.1, d: 0.0}
      wheel_back_left_joint: {p: 0.5, i: 0.1, d: 0.0}
      wheel_back_right_joint: {p: 0.5, i: 0.1, d: 0.0}
